#!/usr/bin/env bash
# cerner_2^5_2019

# Send message to M$ Flow URL to trigger a notification
notify() {
curl -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        -d "{\"message\": \"$1\"}" \
        $LASTCHECK_URL
      }

files=$(git diff --staged --name-only)
gitroot=$(git rev-parse --show-toplevel)
cd $gitroot
if [[ $files =~ .rb|.erb ]]; then
  if [ git ls-files | grep -q Rakefile ]; then
    if [ which bundle ]; then
      bundle exec rake
    else
      rake
    fi
    if [ $? -eq 0 ]; then
      notify "success"
    else
      notify "failure"
      exit 1
    fi
  fi
fi


